name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First job
        id: first
        shell: bash
        run: |
            echo "LS before" >> $GITHUB_OUTPUT
            ls -l >> $GITHUB_OUTPUT
            mkdir -p a b c d
            echo "LS mkdir" >> $GITHUB_OUTPUT
            ls -l >> $GITHUB_OUTPUT
            rm -rf $(find . -mindepth 1 -maxdepth 1 -type d ! -name "a") || true
            echo "LS after" >> $GITHUB_OUTPUT
            ls -l >> $GITHUB_OUTPUT