name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on:
      group: ubuntu-runners
      labels: ubuntu-20.04-16core
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

  Test-Job:
    runs-on: ubuntu-latest
    steps:
      - name: First job
        id: first
        shell: bash
        run: |
            sudo apt install python2.7 -y
            echo "LS before"
            echo $(ls -l)
            mkdir -p a b c d
            echo "LS mkdir"
            echo $(ls -l)
            rm -rf $(find . -mindepth 1 -maxdepth 1 -type d ! -name "a") || true
            echo "LS after"
            echo $(ls -l)
            __current_dir=$PWD
            mkdir -p my_dir
            cd my_dir
            echo "LS my_dir $(ls -l)"
            cd ${__current_dir}
            echo "LS __current_dir $(ls -l)"